export const items = [
    {
      id: 1,
      name: "Intel Core i3",
      category: "Intel",
      price: 900,
      image: "https://example.com/intel-cpu.jpg",
      dateListed: "2024-01-10",
    },
    {
        id: 2,
        name: "Intel Core i5",
        category: "Intel",
        price: 900,
        image: "https://example.com/intel-cpu.jpg",
        dateListed: "2024-02-15",
    },
    {
        id: 3,
        name: "Intel Core i7",
        category: "Intel",
        price: 900,
        image: "https://example.com/intel-cpu.jpg",
        dateListed: "2024-03-20",
    },
    {
        id: 4,
        name: "Intel Core i9",
        category: "Intel",
        price: 900,
        image: "https://example.com/intel-cpu.jpg",
        dateListed: "2024-04-05",
    },
    {
      id: 5,
      name: "AMD Ryzen 3",
      category: "AMD",
      price: 900,
      image: "https://example.com/amd-ryzen.jpg",
      dateListed: "2024-02-01",
    },
    {
        id: 6,
        name: "AMD Ryzen 5",
        category: "AMD",
        price: 900,
        image: "https://example.com/amd-ryzen.jpg",
        dateListed: "2024-03-10",
    },
    {
        id: 7,
        name: "AMD Ryzen 7",
        category: "AMD",
        price: 900,
        image: "https://example.com/amd-ryzen.jpg",
        dateListed: "2024-04-20",
    },
    {
        id: 8,
        name: "AMD Ryzen 9",
        category: "AMD",
        price: 900,
        image: "https://example.com/amd-ryzen.jpg",
        dateListed: "2024-05-01",
    },
    {
      id: 9,
      name: "Server Processors (Xeon)",
      category: "Server Processors",
      price: 900,
      image: "https://example.com/server-cpu.jpg",
      dateListed: "2024-01-25",
    },
    {
        id: 10,
        name: "Server Processors (EPYC)",
        category: "Server Processors",
        price: 900,
        image: "https://example.com/server-cpu.jpg",
        dateListed: "2024-02-28",
    },
];
