export const items = [
  {
    id: 1,
    name: "Intel Core i3/i5/i7/i9",
    category: "CPU",
    price: 900,
    image: "https://example.com/intel-cpu.jpg",
    description: "High-performance Intel processor series, perfect for gaming and professional workloads.",
    sellerReview: 4.8,
    location: "New York, USA",
    dateListed: "2025-03-10",
  },
  {
    id: 2,
    name: "AMD Ryzen 3/5/7/9",
    category: "CPU",
    price: 900,
    image: "https://example.com/amd-ryzen.jpg",
    description: "Powerful AMD Ryzen series with great multitasking performance and efficiency.",
    sellerReview: 4.7,
    location: "Los Angeles, USA",
    dateListed: "2025-03-12",
  },
  {
    id: 3,
    name: "Server Processors (Xeon, EPYC)",
    category: "CPU",
    price: 900,
    image: "https://example.com/server-cpu.jpg",
    description: "Designed for server applications, offering extreme reliability and performance.",
    sellerReview: 4.9,
    location: "Chicago, USA",
    dateListed: "2025-03-15",
  },
  {
    id: 4,
    name: "NVIDIA (GTX, RTX Series)",
    category: "GPU",
    price: 600,
    image: "https://example.com/nvidia-gpu.jpg",
    description: "Latest NVIDIA GPUs, perfect for gaming and AI workloads.",
    sellerReview: 4.6,
    location: "San Francisco, USA",
    dateListed: "2025-03-14",
  },
  {
    id: 5,
    name: "AMD Radeon (RX Series)",
    category: "GPU",
    price: 600,
    image: "https://example.com/amd-radeon.jpg",
    description: "High-performance AMD Radeon graphics cards for gaming and professional use.",
    sellerReview: 4.5,
    location: "Houston, USA",
    dateListed: "2025-03-13",
  },
  {
    id: 6,
    name: "Integrated Graphics",
    category: "GPU",
    price: 600,
    image: "https://example.com/integrated-gpu.jpg",
    description: "Budget-friendly integrated graphics for everyday computing.",
    sellerReview: 4.2,
    location: "Miami, USA",
    dateListed: "2025-03-11",
  },
  {
    id: 7,
    name: "Intel & AMD Compatible",
    category: "Motherboard",
    price: 300,
    image: "https://example.com/motherboard.jpg",
    description: "Versatile motherboard compatible with Intel and AMD processors.",
    sellerReview: 4.7,
    location: "Seattle, USA",
    dateListed: "2025-03-09",
  },
  {
    id: 8,
    name: "ATX, Micro-ATX, Mini-ITX",
    category: "Motherboard",
    price: 300,
    image: "https://example.com/atx-motherboard.jpg",
    description: "Motherboard sizes suitable for various PC builds, from compact to full towers.",
    sellerReview: 4.6,
    location: "Boston, USA",
    dateListed: "2025-03-10",
  },
  {
    id: 9,
    name: "DDR3",
    category: "RAM",
    price: 300,
    image: "https://example.com/ddr3-ram.jpg",
    description: "Reliable DDR3 RAM for older systems and budget builds.",
    sellerReview: 4.4,
    location: "Denver, USA",
    dateListed: "2025-03-08",
  },
  {
    id: 10,
    name: "DDR4",
    category: "RAM",
    price: 150,
    image: "https://example.com/ddr4-ram.jpg",
    description: "Fast and efficient DDR4 RAM for modern systems.",
    sellerReview: 4.8,
    location: "Phoenix, USA",
    dateListed: "2025-03-12",
  },
  {
    id: 11,
    name: "DDR5",
    category: "RAM",
    price: 100,
    image: "https://example.com/ddr5-ram.jpg",
    description: "Next-gen DDR5 RAM for high-performance computing.",
    sellerReview: 4.9,
    location: "Dallas, USA",
    dateListed: "2025-03-14",
  },
];
