export const items = [
  {
    id: 1,
    name: "Intel Core i3/i5/i7/i9",
    category: "CPU",
    price: 900,
    image: "https://example.com/intel-cpu.jpg",
  },
  {
    id: 2,
    name: "AMD Ryzen 3/5/7/9",
    category: "CPU",
    price: 900,
    image: "https://example.com/amd-ryzen.jpg",
  },
  {
    id: 3,
    name: "Server Processors (Xeon, EPYC)",
    category: "CPU",
    price: 900,
    image: "https://example.com/server-cpu.jpg",
  },
  {
    id: 4,
    name: "NVIDIA (GTX, RTX Series)",
    category: "GPU",
    price: 600,
    image: "https://example.com/nvidia-gpu.jpg",
  },
  {
    id: 5,
    name: "AMD Radeon (RX Series)",
    category: "GPU",
    price: 600,
    image: "https://example.com/amd-radeon.jpg",
  },
  {
    id: 6,
    name: "Integrated Graphics",
    category: "GPU",
    price: 600,
    image: "https://example.com/integrated-gpu.jpg",
  },
  {
    id: 7,
    name: "Intel & AMD Compatible",
    category: "Motherboard",
    price: 300,
    image: "https://example.com/motherboard.jpg",
  },
  {
    id: 8,
    name: "ATX, Micro-ATX, Mini-ITX",
    category: "Motherboard",
    price: 300,
    image: "https://example.com/atx-motherboard.jpg",
  },
  {
    id: 9,
    name: "DDR3",
    category: "RAM",
    price: 300,
    image: "https://example.com/ddr3-ram.jpg",
  },
  {
    id: 10,
    name: "DDR4",
    category: "RAM",
    price: 150,
    image: "https://example.com/ddr4-ram.jpg",
  },
  {
    id: 11,
    name: "DDR5",
    category: "RAM",
    price: 100,
    image: "https://example.com/ddr5-ram.jpg",
  },
];
